baseurl = "https://www2.sigsoft.org" # Configure URL. if using gh-pages https://github.com/<username>/hugo-universal-theme URL: https://<username>.github.io/hugo-universal-theme/
title = "The ACM Special Interest Group on Software Engineering"
theme = "hugo-universal-theme"
themesDir = "themes/"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

# not pluralize title pages by default
pluralizelisttitles = false

[menu]

# Main menu
[[menu.main]]
    name       = "About"
    identifier = "menu.abt"
    weight     = 1

[[menu.main]]
    name       = "Executive Committee"
    url        = "/execcontact"
    weight     = 1
    parent     = "menu.abt"

[[menu.main]]
    name       = "CARES Committee"
    url        = "/cares/committee/"
    weight     = 2
    parent     = "menu.abt"

[[menu.main]]
    name       = "SIGSOFT Bylaws"
    url        = "https://www.acm.org/special-interest-groups/volunteer-resources/bylaws/sigsoft-bylaws"
    weight     = 3
    parent     = "menu.abt"

[[menu.main]]
    name       = "Logos"
    url        = "/logos/logos"
    weight     = 4
    parent     = "menu.abt"

[[menu.main]]
    name       = "Contact Us"
    url        = "/contact"
    weight     = 5
    parent     = "menu.abt"



[[menu.main]]
    name       = "Conferences"
    identifier = "menu.conferences"
    weight     = 3

[[menu.main]]
    name       = "Ongoing Conferences"
    url        = "/event"
    weight     = 1
    parent     = "menu.conferences"

[[menu.main]]
    name       = "Program Committee Policy"
    url        = "/PCpolicy"
    weight     = 2
    parent     = "menu.conferences"

[[menu.main]]
    name       = "Open Science Policy"
    url        = "https://github.com/acmsigsoft/open-science-policies"
    weight     = 3
    parent     = "menu.conferences"



[[menu.main]]
    name       = "Community"
    identifier = "menu.community"
    weight     = 2

[[menu.main]]
    name       = "Blog"
    url        = "https://sigsoft.medium.com/"
    weight     = 1
    parent     = "menu.community"

[[menu.main]]
    name       = "Mastodon"
    url        = "https://social.sigsoft.org/public/local"
    weight     = 2
    parent     = "menu.community"

[[menu.main]]
    name       = "SEWORLD Mailing List"
    url        = "/seworld"
    weight     = 3
    parent     = "menu.community"



[[menu.main]]
    name       = "Publications"
    identifier = "menu.pubs"
    weight     = 4

[[menu.main]]
    name       = "ACM Digital Library: SIGSOFT"
    url        = "https://dl.acm.org/sig/sigsoft"
    weight     = 1
    parent     = "menu.pubs"

[[menu.main]]
    name       = "Proceedings of the ACM on Software Engineering (PACMSE)"
    url        = "https://dl.acm.org/journal/pacmse"
    weight     = 2
    parent     = "menu.pubs"

[[menu.main]]
    name       = "Software Engineering Notes (SEN)"
    url        = "/SEN/SEN"
    weight     = 3
    parent     = "menu.pubs"

[[menu.main]]
    name       = "Research Highlights"
    url        = "https://www.sigsoft.org/resources/highlights.html"
    weight     = 4
    parent     = "menu.pubs"



[[menu.main]]
    name       = "Awards"
    identifier = "menu.features"
    weight     = 5

[[menu.main]]
    name       = "SIGSOFT Awards"
    identifier = "section.awards"
    url        = ""
    weight     = 1
    parent     = "menu.features"
    post       = 1

[[menu.main]]
    name       = "Conference Awards"
    identifier = "section.conference"
    url        = ""
    weight     = 2
    parent     = "menu.features"
    post       = 2

[[menu.main]]
    name       = "Distinguished Service"
    url        = "/awards/distinguishedService"
    weight     = 1
    parent     = "section.awards"

[[menu.main]]
    name       = "Outstanding Research"
    url        = "/awards/outstandingResearch"
    weight     = 2
    parent     = "section.awards"

[[menu.main]]
    name       = "Influential Educator"
    url        = "/awards/influentialEducator"
    weight     = 3
    parent     = "section.awards"

[[menu.main]]
    name       = "Impact Paper"
    url        = "/awards/impactPaper"
    weight     = 4
    parent     = "section.awards"

[[menu.main]]
    name       = "Outstanding Doctoral Dissertation"
    url        = "/awards/dissertation"
    weight     = 5
    parent     = "section.awards"

[[menu.main]]
    name       = "Early Career Researcher"
    url        = "/awards/earlyCareerResearcher"
    weight     = 6
    parent     = "section.awards"

[[menu.main]]
    name       = "ACM SIGSOFT - SIGBED Frank Anger Memorial"
    url        = "/awards/anger"
    weight     = 7
    parent     = "section.awards"

[[menu.main]]
    name       = "ACM SIGSOFT Distinguished Paper"
    url        = "/awards/distinguishedPaper"
    weight     = 1
    parent     = "section.conference"

[[menu.main]]
    name       = "ICSE Most Influential Paper"
    url        = "https://www.icse-conferences.org/mostinfluential.html"
    weight     = 2
    parent     = "section.conference"

[[menu.main]]
    name       = "ESEC/FSE Test of Time"
    url        = "https://www.esec-fse.org/test_of_time_awards"
    weight     = 3
    parent     = "section.conference"

[[menu.main]]
    name       = "ASE Most Influential Paper"
    url        = "https://ase-conferences.org/most-influential-papers.html"
    weight     = 4
    parent     = "section.conference"

[[menu.main]]
    name       = "ISSTA Impact and Retrospective"
    url        = "https://www.issta.org/#impact"
    weight     = 5
    parent     = "section.conference"

[[menu.main]]
    name       = "Programs and Activities"
    identifier = "menu.programs_activities"
    weight     = 6

[[menu.main]]
    name       = "Overview"
    weight     = 1
    parent     = "menu.programs_activities"
    url        = "/activities/overview"

[[menu.main]]
    name       = "CARES"
    url        = "/cares/sigsoft_cares"
    weight     = 2
    parent     = "menu.programs_activities"

[[menu.main]]
    name       = "Travel Support and Childcare Assustance (CAPS)"
    url        = "/activities/capsmain"
    weight     = 3
    parent     = "menu.programs_activities"

[[menu.main]]
    name       = "Webinars"
    url        = "/activities/webinarsmain"
    weight     = 4
    parent     = "menu.programs_activities"

[[menu.main]]
    name       = "Summer/Winter Schools"
    url        = "/activities/schools"
    weight     = 5
    parent     = "menu.programs_activities"

[[menu.main]]
    name       = "Join"
    identifier = "menu.join"
    weight     = 7

[[menu.main]]
    name       = "Join SIGSOFT"
    url        = "https://www.acm.org/special-interest-groups/sigs/sigsoft"
    weight     = 1
    parent     = "menu.join"

[[menu.main]]
    name       = "Volunteers"
    url        = "/volunteers"
    weight     = 2
    parent     = "menu.join"

    

# Top bar social links menu

[[menu.topbar]]
    weight = 2
    name = "GitHub"
    url = "https://github.com/acmsigsoft"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 3
    name = "Facebook"
    url = "https://www.facebook.com/sigsoft/"
    pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 4
    name = "Twitter"
    url = "https://twitter.com/sigsoft"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 4
    name = "Linkedin"
    url = "https://www.linkedin.com/company/acm-sigsoft/"
    pre = "<i class='fab fa-2x fa-linkedin'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "SIGSOFT template made by Raula using Hugo"

    # Social media
    facebook_site = "sigsoft" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "sigsoft" # the Twitter handle of your site (without the '@')
    default_sharing_image = "/img/sigsoft.png"

    #Â Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"

    formspree_action = "https://formspree.io/sample/of/endpoint"
    contact_form_ajax = false

    about_us = "<p>The ACM Special Interest Group on Software Engineering provides a forum for computing professionals from industry, government and academia to examine principles, practices, and new research results in software engineering.</p>"
    copyright = "Copyright (c) 2020 - 2025, SIGSOFT; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    dropdown_mouse_over = false

    disabled_logo = false
    logo_text = "SIGSOFT"

    logo = "img/sigsoft.png"
    logo_small = "img/sigsoft.png"
    contact_url = "/contact"

[permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">The ACM Special Interest Group on Software Engineering</p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

#[params.carouselCustomers]
#    items = 6
#    auto_play = false
#    slide_speed = 2000
#   pagination_speed = 1000

[params.carouselTestimonials]
    items = 4
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = false
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.features]
    enable = false
    cols = 3 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.

[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more information take a look at the README.
    title = "2025 SIGSOFT Awards"
    subtitle = "We would like to heartily congratulate the winners of the various ACM SIGSOFT awards:"

[params.see_more]
    enable = true
    icon = "far fa-file-alt"
    title = "Mission Statement"
    subtitle = "The ACM Special Interest Group on Software Engineering seeks to improve our ability to engineer software by stimulating interaction among practitioners, researchers, and educators; by fostering the professional development of software engineers; and by representing software engineers to professional, legal, and political entities."
    link_url = "https://www2.sigsoft.org/"
    link_text = "Homepage"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more information take a look at the README.
    title = "CARES Committee Members"
    subtitle = ""

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
