baseurl = "https://devcows.github.io/hugo-universal-theme/" # Configure URL. if using gh-pages https://github.com/<username>/hugo-universal-theme URL: https://<username>.github.io/hugo-universal-theme/
title = "The ACM Special Interest Group on Software Engineering"
theme = "hugo-universal-theme"
themesDir = "themes/"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

# not pluralize title pages by default
pluralizelisttitles = false

[menu]

# Main menu
[[menu.main]]
    name       = "About"
    identifier = "menu.abt"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "Executive Committee"
    url        = "/execcontact"
    weight     = 1
    parent     = "menu.abt"

[[menu.main]]
    name       = "SIGSOFT Bylaws"
    url        = "https://www.acm.org/special-interest-groups/volunteer-resources/bylaws/sigsoft-bylaws"
    weight     = 2
    parent     = "menu.abt"


[[menu.main]]
    name       = "Awards"
    identifier = "menu.features"
    weight     = 3

[[menu.main]]
    name       = "SIGSOFT Awards"
    identifier = "section.awards"
    url        = ""
    weight     = 1
    parent     = "menu.features"
    post       = 1

[[menu.main]]
    name       = "Conference Awards"
    identifier = "section.conference"
    url        = ""
    weight     = 2
    parent     = "menu.features"
    post       = 2

[[menu.main]]
    name       = "Distinguished Service"
    url        = "/Awards/distinguishedService"
    weight     = 1
    parent     = "section.awards"

[[menu.main]]
    name       = "Outstanding Research"
    url        = "/Awards/outstandingResearch"
    weight     = 2
    parent     = "section.awards"

[[menu.main]]
    name       = "Influential Educator"
    url        = "/Awards/influentialEducator"
    weight     = 3
    parent     = "section.awards"

[[menu.main]]
    name       = "Impact Paper"
    url        = "/Awards/impactPaper"
    weight     = 4
    parent     = "section.awards"

[[menu.main]]
    name       = "Outstanding Doctoral Dissertation"
    url        = "/Awards/dissertation"
    weight     = 5
    parent     = "section.awards"

[[menu.main]]
    name       = "Early Career Researcher"
    url        = "/Awards/earlyCareerResearcher"
    weight     = 6
    parent     = "section.awards"

[[menu.main]]
    name       = "ACM SIGSOFT - SIGBED Frank Anger Memorial"
    url        = "/Awards/anger"
    weight     = 7
    parent     = "section.awards"

[[menu.main]]
    name       = "ICSE Most Influential Paper"
    url        = "https://www.sigsoft.org/awards/icseMIPAward.html"
    weight     = 1
    parent     = "section.conference"

[[menu.main]]
    name       = "ESEC/FSE Test of Time"
    url        = "http://www.esec-fse.org/test_of_time_awards"
    weight     = 2
    parent     = "section.conference"

[[menu.main]]
    name       = "ASE Most Influential Paper"
    url        = ""
    weight     = 3
    parent     = "section.conference"

[[menu.main]]
    name       = "ISSTA Impact and Retrospective"
    url        = ""
    weight     = 4
    parent     = "section.conference"

[[menu.main]]
    name       = "Distinguished Paper"
    url        = "https://www.sigsoft.org/awards/distinguishedPaperAward.html"
    weight     = 5
    parent     = "section.conference"

[[menu.main]]
    name       = "CARES"
    identifier = "menu.cares"
    weight     = 3

[[menu.main]]
    name       = "Purpose and Annual Reporting"
    url        = "/cares/SIGSOFT_CARES"
    weight     = 1
    parent     = "menu.cares"

[[menu.main]]
    name       = "Resources"
    url        = "/cares/RESOURCES"
    weight     = 2
    parent     = "menu.cares"

[[menu.main]]
    name       = "Bylaws"
    url        = "/cares/ByLAWS"
    weight     = 3
    parent     = "menu.cares"

[[menu.main]]
    name       = "CAPS"
    identifier = "menu.allpages"
    url        = "/CAPS/CAPSMAIN"
    weight     = 4

[[menu.main]]
    name       = "Blog"
    identifier = "menu.blog"
    url        = "https://sigsoft.medium.com/"
    weight     = 5

[[menu.main]]
    name       = "Webinars"
    identifier = "menu.webinars"
    url        = "/WEBINARS/WEBINARSMAIN"
    weight     = 6

[[menu.main]]
    identifier = "contact"
    name       = "Contact"
    url        = "/contact"
    weight     = 7


# Top bar social links menu


[[menu.topbar]]
    weight = 2
    name = "GitHub"
    url = "https://github.com/devcows/hugo-universal-theme"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 3
    name = "Facebook"
    url = "http://facebook.com"
    pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 4
    name = "Twitter"
    url = "http://twitter.com"
    pre = "<i class='fab fa-2x fa-twitter'></i>"


[params]
    viewMorePostLink = "/blog/"
    author = "DevCows"
    defaultKeywords = ["raux", "hugo", "go"]
    mainSections = ["blog"]
    defaultDescription = "Site template made by Raula using Hugo"

    # Social media
    facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "GoHugoIO" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"

    #Â Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"

    formspree_action = "https://formspree.io/sample/of/endpoint"
    contact_form_ajax = false

    about_us = "<p>The ACM Special Interest Group on Software Engineering provides a forum for computing professionals from industry, government and academia to examine principles, practices, and new research results in software engineering.</p>"
    copyright = "Copyright (c) 2020 - 2023, SIGSOFT; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    dropdown_mouse_over = false

    disabled_logo = false
    logo_text = "SIGSOFT"

    logo = "img/sigsoft.png"
    logo_small = "img/sigsoft.png"
    contact_url = "/contact"

[permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">The ACM Special Interest Group on Software Engineering</p>
      <p class="hidden-md hidden-lg"><a href="tel:+420 777 555 333" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="mailto:hello@universal.com" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

#[params.carouselCustomers]
#    items = 6
#    auto_play = false
#    slide_speed = 2000
#   pagination_speed = 1000

[params.carouselTestimonials]
    items = 5
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = false
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.features]
    enable = false
    cols = 3 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.

[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more information take a look at the README.
    title = "2023 SIGSOFT Awards"
    subtitle = "We would like to heartily congratulate the winners of the various ACM SIGSOFT awards:"

[params.see_more]
    enable = true
    icon = "far fa-file-alt"
    title = "Mission Statement"
    subtitle = "The ACM Special Interest Group on Software Engineering seeks to improve our ability to engineer software by stimulating interaction among practitioners, researchers, and educators; by fostering the professional development of software engineers; and by representing software engineers to professional, legal, and political entities."
    link_url = "https://www.sigsoft.org/index.html"
    link_text = "Homepage"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more information take a look at the README.
    title = "CARES Committee Members"
    subtitle = ""

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
